[package]
name = "mika-webcontainer"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.9"
js-sys = "0.3.68"
rand = "0.8.5"
regex = "1.10.6"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
wasm-bindgen = "0.2.91"

[lib]
crate-type = ["cdylib"]


